# -*- coding: utf-8 -*-
"""[Scrapping] Submission Proyek Analisis Sentimen Review Aplikasi Webtoon_MC006D5X1393.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ua0f0Dtx6meeeODyypJxLv9s6ptK_tfy

## **Tugas Proyek Analisis Setimen**
Nama : Nisrina Fatimah Parisya

ID Cohort : MC006D5X1393

Tema Tugas : Analisis Sentimen pada Aplikasi

# Scraping Dataset
"""

## Melakukan installasi google scraper
!pip install google-play-scraper
from google_play_scraper import reviews_all

from google_play_scraper import app, reviews, Sort, reviews_all

import nltk

nltk.download('punkt_tab', force=True)
nltk.download('stopwords', force=True)
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

from google_play_scraper import app, reviews, Sort, reviews_all
# ambil data ulasan aplikasi webtoon
result = reviews_all(
    'com.naver.linewebtoon',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=1000
)

import csv

with open('review_webtoon.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Ulasan'])
    for ulasan in result:
        writer.writerow([ulasan['content']])

import pandas as pd

df_webtoon_review = pd.DataFrame(result)
df_webtoon_review.head()
df_webtoon_review.shape
df_webtoon_review.to_csv('review_webtoon.csv', index=False)

# hitung jumlah baris kolom di df
total_review, total_kolom = df_webtoon_review.shape
df_webtoon_review.head()